std/haxe/macro/ExprTools.hx

This may seem unnecessary, because why would someone hard-code `true ? 413 : 612` when they could just write `413`? But consider conditional compilation. For example:
moveSpeed = #if alwaysRun true #else shiftHeld() #end ? 50 : 25;
If the `alwaysRun` flag is set, then `moveSpeed` will always be 50. And this can be determined at compile time. However, the expression cannot be hard-coded as "`moveSpeed = 50;`".

Added support for conditionals to getValue()

---

std/cs/internal/Null.hx

Calling "v is ValueType" on a value type requires boxing it, whereas typeof(T).IsValueType does not require boxing.
@waneck

[cs] Remove unnecessary GC allocation inside Null.

---

std/flash/display/GraphicsPathCommand.hx

The command `GraphicsPath.Command.CUBIC_CURVE_TO` wasn't in the flash externs.
~~While everywhere else the `cubicCurveTo()` is a flash11 feature, in the [Adobe documentation](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/GraphicsPathCommand.html#CUBIC_CURVE_TO) this particular field says that it works on a flash 10 runtime so I simply added it without `@:require(flash11)`~~ The docs were wrong

Added GraphicsPathCommand.CUBIC_CURVE_TO

---

std/cs/internal/Null.hx

Cache result of IsValueType - much faster runtime perf.
@nadako

[cs] Faster version of ValueType check in Null

---

analyzer.ml
common.ml
optimizer.ml
tests/RunCi.hx
tests/optimization/src/TestJs.hx
tests/optimization/src/TestLocalDce.hx
tests/unit/src/unit/TestCSharp.hx

Supports loop unrolling in `for (x in [1, 2, 3])` and comes with some minor analyzer adjustments.
Technically we're feature-frozen, but I'm willing to make an exception because this feature was requested by a Haxe Foundation partner.

Loop unrolling

---

std/haxe/crypto/Sha1.hx
std/haxe/crypto/Sha256.hx

Md5's hex representation is little-endian, so cannot use the big-endian StringTools.hex for it; but this should simplify these two classes a little bit.

Use StringTools.hex for Sha1 and Sha256

---

gencommon.ml
std/cs/internal/HxObject.hx
std/java/internal/HxObject.hx

I'm trying to make people use haxe enums, but we need interop with native C# code, so we need to use `getTag` method a lot. It was generating a bunch of ugly reflection calls which are VERY slow (77ms). I tried to make it use concrete target-specific reflection for enums, but that didn't help much (54ms), so I went another way and just made haxe generate overriden `getTag` method for every concrete `Enum` subclass which does simply access its static `constructs` array, which works a lot faster (2ms).
For example, `haxe.ds.Option` now generates the following C# code:
```cs
public override string getTag() {
return global::haxe.lang.Runtime.toString(global::haxe.ds.Option.constructs.__unsafe_get(this.index));
}
```
Now, the 2 ms overhead is caused by `Runtime.toString` call which I don't yet …

[cs/java] generate specific getTag methods for enum classes to avoid using reflection

---

std/haxe/io/ArrayBufferView.hx
std/haxe/io/BytesBuffer.hx
std/haxe/io/BytesData.hx
std/haxe/io/BytesInput.hx
std/haxe/io/Float32Array.hx
std/haxe/io/Input.hx
std/haxe/io/Uint8Array.hx
std/js/_std/haxe/io/Bytes.hx
std/js/html/compat/ArrayBuffer.hx
std/js/html/compat/Float32Array.hx
std/js/html/compat/Uint8Array.hx
tests/RunCi.hx
tests/unit/src/unitstd/haxe/io/Float32Array.unit.hx
tests/unit/src/unitstd/haxe/io/Uint8Array.unit.hx

This is a proposal to implement typed arrays in a cross platform manner, following the JS way of doing.
I'm trying to take proper attention at correctly integrating it together the bytes "views" with the static buffer which is haxe.io.Bytes.
Please note that in order to support this I had to change the haxe.io.BytesData in JS from Uint8Array to ArrayBuffer, which match better our definition. This will most likely require additional compat support for IE8.

cross platform typed array proposal

---

std/php/_std/haxe/ds/StringMap.hx
tests/unit/src/unit/issues/Issue3462.hx

As promised in #3898
Uses a `stdClass` as underlying data structure. This should keep the keys as strings.

modified StringMap implementation for PHP

---

genswf9.ml
tests/unit/src/unit/issues/Issue2736.hx

AVM2 shift op always returns an int, even for e.g. UInt << Int. This change coerces them to the type of the first operand. Fixes #2736.

[swf9] Fix UInt shift behavior

---

analyzer.ml
ast.ml
codegen.ml
common.ml
extra/CHANGES.txt
filters.ml
interp.ml
matcher.ml
optimizer.ml
std/haxe/macro/Context.hx
tests/unit/src/unit/issues/Issue3914.hx
typeload.ml
typer.ml

This adds new `Context.storeTypedExpr` method that allows one to store a typed expression in the context and return a syntax-level expression to be returned from a macro that will be replaced by the stored expression when typing.
This allows to "properly" deal with issues like the one described in #3906, when we want to return a (part of) typed expression from a macro.
I would like this to be included in 3.2 because otherwise I would have to find some ugly workarounds for "regressions" in my project code, like this one https://gist.github.com/nadako/54f9cac9de1515746950

add Context.storeTypedExpr

---

genas3.ml
gencs.ml
genjava.ml
genphp.ml
genpy.ml
std/cs/_std/haxe/Resource.hx
std/java/_std/haxe/Resource.hx
std/php/_std/haxe/Resource.hx
tests/unit/compile-each.hxml
tests/unit/src/unit/TestResource.hx

This applies base64 encoding on all targets that write resources by-name to the file system. There are two complementary PRs for hxjava and hxcs:
https://github.com/HaxeFoundation/hxcs/pull/16
https://github.com/HaxeFoundation/hxjava/pull/13
(closes #3760)

Resource name base 64

---

ast.ml
common.ml
genjava.ml
tests/unit/native_java/src/haxe/test/MyClass.java
tests/unit/src/unit/TestCSharp.hx
tests/unit/src/unit/TestJava.hx
typeload.ml

Added @:meta implementation for Java. Closes #2065 
Please review - I've added some platform-specific code to typeload.ml, and I don't think this can be avoided, sadly

[java/cs] Added @:strict metadata that performs type checking on C#/Java

---

gencommon.ml
gencs.ml
genjava.ml
std/cs/internal/FieldLookup.hx
std/java/internal/FieldLookup.hx

Subj. This features less allocation per structure and a little faster lookup due to less checks. On C# should work both with and without `-D erase-generics`.
@waneck please review

[cs/java] use native arrays for DynamicObject (see #3945)

---

std/sys/db/Manager.hx

Fixes glitch where:
- existing record has non-null value
- you have a sys.db.Object with no cache (created manually, via remoting etc)
- set the value to null, try to update
- previous value remains.
Please note the private method isBinary() is now no longer used and could
be removed, though it may be useful in future.

In sys.db.Manager.doUpdate(), if cache is null, update all fields

---

std/haxe/macro/Compiler.hx

Updated documentation to reflect usage of optional parameter in `Compiler.include()`.

fix issue #3821

---

filters.ml
genjs.ml
std/haxe/CallStack.hx
std/js/Boot.hx
tests/optimization/src/TestJs.hx
tests/unit/src/unitstd/haxe/CallStack.unit.hx

See #2854 and #3062. This wraps thrown objects that are not instances of `js.Error` in its special subclass, and saves in catch so we can get the stack trace for `haxe.CallStack.exceptionStack`.
```haxe
class Main {
try {
throw false;
} catch (e:Dynamic) {
trace(e);
}
}
}
```
now generates
```js
Main.main = function() {
try {
throw new js__$Boot_HaxeError(false);
} catch( e ) {
if (e instanceof js__$Boot_HaxeError) e = e.val;
console.log(e);
}
};
```
but only if we did any wraping, so e.g.
```haxe
class Main {
try {
throw new js.Error();
} catch (e:Dynamic) {
trace(e);
}
}
}
```
generates simple
```js
Main.main = function() {
try {
throw new Error();
} catch( e ) {
console.log(e);
}
};
```
now if we use `haxe.Callstack.exceptionStack` …

haxe.CallStack.exceptionStack for js

---

std/haxe/crypto/BaseCode.hx
tests/unit/src/unit/TestMisc.hx

For now, don't use the base_encode and base_decode primitives in interp;
they have only been implemented to handle hex and base64 variants.
Instead, use the cross-platform encoding/decoding methods written in
Haxe.

Better support for BaseCode on the interpreter

---

std/Xml.hx
tests/unit/src/unit/issues/Issue4094.hx

Summary of changes:
- When doing insertChild() remove from old location/parent
- When doing insertChild() update .parent
- When doing removeChild() set child.parent to null
- More precise documentation of behaviour in the comments
- Unit tests to verify this behaviour
Fixes #4094

Improvements to new XML class' DOM manipulation functions.

---

std/haxe/ds/Vector.hx

As it is, it causes a compiler error for flash9

Use flash.Vector.ofArray in haxe.ds.Vector only for flash10.

---

Makefile
Makefile.version_extra
Makefile.win

I tested in my machines, including Windows (cygwin and command prompt) and Mac.
@Simn would you check whether it works for you?

Fixed `make ADD_REVISION=1`

---

std/haxe/Http.hx

New hxssl format for tls socket. Neko stays the same for backwards compatibility, but should eventually move to sys.ssl.Socket as well.

Https support for cpp

---

std/Math.hx
std/Std.hx

Added ` on several places since that causes italic texts (because of markdown), and make it a bit more consistant.

Small documentation fixes

---

main.ml
typecore.ml

This error is produced by invalid imports. A .hx module can contain any type (abstract, typedef, enum), not just classes.

"Class not found" error msg should be "Type not found"

---

common.ml
main.ml

- dce docs now mention the default value
- the docs on --help and --helpDefines for dce are now consistent
- it's now clearer that -D var=value is valid

--help / --help-defines: dce and -D improvemnts

---

common.ml

It seems like this meta is used for two different things - since one of them is internal and not displayed on --help-metas, it makes more sense to document the one that's public API instead.
The description is from http://haxe.org/manual/cr-metadata.html.

MetaInfo.to_string: document @:enum abstract meta instead of internal one

---

std/haxe/macro/Context.hx

The previous wording didn't make it clear enough that the function actually tries to unify the types. It could be mistaken as just performing a check without side-effects.

Clearer description for Context.unify()

---

std/php/Boot.hx

The current method to check for the existence of dynamic fields:
isset($o->__dynamics[$field])
will (unintentionally) trigger the magic __get method if it is defined on the object. Objects translated from Haxe do not currently contain this magic, but classes extending them can. I added an extra check:
isset($o->__dynamics)
before the above to make sure magic won't be activated during this call.
Background: it might seem like an edge case, but I'm encountering this problem in a very real situation. I'm using Haxe objects as model classes in a multi-platform application. On the PHP-side Doctrine is managing these objects. Doctrine's lazy loading functionality is implemented with proxy classes, which extend the model classes (which are the ones compiled from Haxe in my case). The proxy …

Safeguard in reflection not to trigger magic __get in subclasses unintentionally.

---

std/String.hx

Small fix for API documentation, `[delimiter)` is weird. Also added some `

String documentation additions

---

std/python/_std/EReg.hx
std/python/_std/String.hx
std/python/_std/StringBuf.hx
std/python/_std/sys/io/File.hx
std/python/_std/sys/net/Host.hx

None of these target-specific classes should have documentation.
It adds double fields to the API documentation, see for example http://api.haxe.org/String.html#split

Remove python/_std documentation

---

typeload.ml

It would let us define JS externs easier. For example there are 8 methods in jQuery that use the same name for both static and instance.
PS. Look like it has already been allowed for java native class. So why not allow it for extern class as well? ;)

Allow extern to have field name that is used for both static and instance

---

genjava.ml
std/java/_std/sys/net/Socket.hx

- Rewrite enumeration member name when it is a Java reserved keyword and is used as a case in a switch.
- For Java, handle host() call where socket is a ServerSocket.

Java library and compiler bug fixes

---

std/haxe/io/Path.hx

Some methods in haxe.oi.Path don't have explicit return type.
This makes the autocompletion don't work properly.

Explicit return type in haxe.oi.Path

---

common.ml
genjs.ml
interp.ml
std/haxe/macro/Compiler.hx
tests/unit/src/unit/issues/Issue4419.hx
tests/unit/src/unit/issues/misc/Issue4419External.js

Currently `haxe.macro.Compiler.includeFile()` includes the input file into the call site, where is usually inside `__init__`. It is problematic:
Haxe by default generate JS output in strict mode. But the input file (e.g. [jQuery](https://github.com/jquery/jquery/issues/1779)!) may not be strict mode compatible, thus there will be run-time error being thrown.
Since the haxe class members are defined before `__init__`s, we cannot extend an external class. Example:
```js
// external.js
var External = function() { };
```
```haxe
extern class External {
static function __init__():Void {
haxe.macro.Compiler.includeFile("external.js");
}
}
class Test extends External {
static function main():Void {
trace("ok");
}
}
```
JS output:
```js
// Generated by Haxe
(function (console) { "use strict"; …
```

Allow to specify includeFile position.

---

std/haxe/Int64.hx
tests/unit/src/unit/TestInt64.hx

Problem was: --9223372036854775808 = -9223372036854775808 .
Without this fix the new test fails:
TestInt64.hx:101: --9-2-2-3-3-7-20-3-6-8-5-4-7-7-5-80-8 should be -9223372036854775808

Fix Int64.toString issue for boundary value.

---

std/haxe/Int64.hx
tests/unit/src/unit/TestInt64.hx

Ensure immutability of Int64 on platforms without native
support.
Fixes #4496.

[Int64] Fix behavior of increment ops.

---

gencpp.ml

hxcpp's `HX_STACK_FRAME` takes a `const char* fullName` that are used in Debug.h's stack class. It looks like the only thing using these (in hxcpp) is the `Profiler` and `Telemetry` classes.
In the case of lambdas, the class seems to always be `*` while the function name is of the form `_Function_#_#`, creating a fullName, e.g. `*._Function_1_2`
This is unfriendly for debugging, locating these lambdas is difficult.
This commit adds a `(filename:line#)` suffix to the fullName when class is `*` (this should only be lambdas), so that the fullName becomes e.g. `*._Function_1_2 (openfl/_internal/text/TextEngine.hx:634)`
Again, this is used in HX_STACK_FRAME calls, e.g.:
```
HX_STACK_FRAME("*","_Function_1_2",0x5200ed38,"*._Function_1_2 …
```

Add filename & line # to HX_STACK_FRAME's fullName

---

std/haxe/io/Bytes.hx

Previously, Bytes.alloc's underlying array would use non-exact sizing designed to prepare for array growth, allocating 1.5x the memory it needs. Use cpp.NativeArray.setSize to allocate with an exact size.
This reaches parity with other platforms that allocate exact-sized arrays.

[cpp] haxe.io.Bytes.alloc use exact size

---

std/cpp/_std/sys/net/Host.hx
std/cs/_std/sys/net/Host.hx
std/java/_std/sys/net/Host.hx
std/neko/_std/sys/net/Host.hx
std/php/_std/sys/net/Host.hx
std/python/_std/sys/net/Host.hx
std/sys/net/Host.hx

Makes a `host` property available in `sys.net.Host`. The original named host is needed for certificate verification in hxssl.

Allow access to the provided named host in sys.net.Host 

---

std/php/Boot.hx
tests/unit/src/unit/issues/Issue4571.hx

This seems to fix these issues in PHP:
https://gist.github.com/clemos/fc48d8076d936531a386#file-test-hx-L14-L18
Please review carefully, as I'm not at all an expert in bit manipulation :p

[php] right shift : return left operand if right operand is 0 in PHP

---

std/haxe/macro/Context.hx

Decided to remove the incorrectly spelled version of `resource` since it's already mentioned (and spelled correctly) in the previous part of the sentence.

Documentation typo fix

---

std/cpp/Prime.hx

It was generating `Callable<cpp.Void->Int>` for `Prime.load("some", "func", "i")` which could not be simply called with `.call()`.

[cpp] fix zero-argument functions in CFFIPrime

---

std/js/_std/haxe/ds/StringMap.hx
tests/unit/src/unit/issues/Issue4579.hx

The toString method in js StringMap was adding an extra ", " to the end of the list
Demo of issue http://try.haxe.org/#9A58e

[js] Prevents StringMap's toString() appending an extra ", "

---

std/List.hx
tests/optimization/src/TestJs.hx

Subj. I'm not sure why it was implemented using `Array<Dynamic>` in the first place. I haven't really done any benchmarks, but I'm pretty sure that at least on static targets, it's much better to use a simple node class instead of Array (considering its internal bound-checking and buffer allocation). Actually, I wouldn't be surprised if it performs better on modern JS engines like V8 as well (due to hidden class optimizations).

use ListNode class instead of Array<Dynamic> as container objects for List elements

---

std/haxe/xml/Parser.hx

This patch adds line number and character position information to exceptions thrown on XML parsing errors, e.g.
Duplicate attribute [width] at line 19 char 24
Called from haxe.xml.Parser::doParse line 223
Called from haxe.xml.Parser::doParse line 267
Called from haxe.xml.Parser::parse line 76
Called from Xml::parse line 44

report line number and char position on xml parsing errors

---

std/haxe/remoting/ExternalConnection.hx

ExternalConnection was still calling javascript code as if js-unflatten
flag was used. Now selects correct code using preprocessor if statement.

Accomodate js-flatten use in ExternalConnection

---

analyzer.ml
filters.ml
optimizer.ml
tests/unit/compile-each.hxml

This pull request changes the filters so that the analyzer transformations (but not optimizations) are always run. This does a lot of code-cleanup for eliminating temporary variables. Here are some encouraging stats for unit.js:
Compilation  | Size   | $this | Time
------------ | ------ | ----- | ------
Old default  | 1690kb | 798   | 4.065s
Old analyzer | 1670kb | 7     | 6.523s
New default  | 1648kb | 10    | 3.942s
New analyzer | 1632kb | 10    | 4.370s
This loses the JS inlining restriction and closes #1827 among other things!

Always use analyzer transformations

---

codegen.ml
matcher.ml
typecore.ml
typeload.ml
typer.ml

This pull requests gets rid of `WithTypeResume` and instead adds `in_call_args : bool` to the typing context. If a unification fails while `in_call_args = true`, a `WithTypeError` is raised and handled accordingly.
This addresses the fact that not all overload-related unification failures are caused by a direct unification of something against the expected argument type, such as the initial examples in #3452.
Naturally, we still want to detect if there's something wrong with one of the argument expressions regardless of overloads. For this we simply check if all overload resolution attempts resulted in the exact same error message. By definition this must mean that the error is invariant with regards to the overloads themselves, so we can just give a normal error:
```haxe
class Main { …
```

Improved resume

---

interp.ml

Otherwise, any class that was added thanks to `addClassPath` won't be able to have macro functions in it.

Compiler.addClassPath: Also add the class path to the macro context

---

genphp.ml

The `yield` keyword should be avoided in php output:
http://php.net/manual/en/language.generators.syntax.php#control-structures.yield

Added yield to reserved php keywords

---

std/js/Lib.hx

This change prevent the following warning when using [webpack](https://webpack.github.io) with haxe generated JavaScript files.
```
WARNING in ./~/microbuilder-js/index.js
Critical dependencies:
6183:8-23 the request of a dependency is an expression
@ ./~/microbuilder-js/index.js 6183:8-23
```

Make require an external function

---

extra/CHANGES.txt

Master was currently 20 commits ahead of dev because of the cherry-picked commits for 3.2.1. `CHANGES.txt` on dev was also missing the release notes for 3.2.1, which this takes care of, and master would have to be merged back to dev for the next release anyway.

Merge master into dev

---

ast.ml
common.ml
genphp.ml
typeload.ml

Some attempts in ocaml hackery, not ready yet:
Modify gen_member_access in genphp to deal with global namespace
Add metadata @:phpConstants for dealing with constants

PHP externs in the global namespace

---

src/generators/genjs.ml
src/main.ml
src/typing/common.ml
std/js/_std/Array.hx
std/js/_std/HxOverrides.hx
std/js/_std/Std.hx
tests/RunCi.hx
tests/unit/src/RunSauceLabs.hx

See #4961
This PR adds the new define `-D js-es=<version>` that allows setting the ECMAScript compilance version and deprecates `-D js-es5` which is now automatically set for all `js-es` values greater than or equal 5 for backward compatibility. It also sets default ES version to 5.
This should be safe for 3.3, I think.
I wonder if we could/should warn about usage of deprecated compiler defines, i.e. emit a deprecation message on `#if js_es5` and `-D js-es5`.

[js] use ES5 by default, add -D js-es=<ver>

---

std/haxe/Http.hx

I add `Connection: close` in request headers, as defined in RFC :
> HTTP/1.1 applications that do not support persistent connections MUST include the "close" connection option in every message.
For body reading, I first check if the message is chunked, as we should ignore Content-Length in this case. RFC says :
> If a message is received with both a Transfer-Encoding header field and a Content-Length header field, the latter MUST be ignored.
I don't use `shutdown()` where transfer is chunked : we don't need an `Eof` in this case, a chunked message is ended by a 0-length chunk. In fact I think an Eof must be seen as an error here.
I left the `shutdown()` when we need an `Eof`. That should only concern HTTP 1.0 servers, as HTTP 1.1 requires Content-Length or chunked transfer :
> In order to …

Improve handling of Transfer-encoding: chunked (closes #4950)

---

src/generators/genphp.ml
tests/unit/src/unit/issues/Issue4810.hx

This fixes #4810 
Seems like the behaviour was [already correct](https://github.com/benmerckx/haxe/blob/86ebc5d176f1392936f0b31395a6eecb0942bb8a/src/generators/genphp.ml#L1888) for variables created with (get, set). Only (get, ..) and (.., set) were not handled correctly.

Properly escape php get/set fields

---

std/haxe/Http.hx

Set withCredentials before open() can throws an exception.
I've seen this behavior on old versions of Safari.
See specifications here : https://xhr.spec.whatwg.org/#the-withcredentials-attribute

Fix withCredentials on old Safari

---

std/haxe/Http.hx
std/neko/_std/sys/ssl/Certificate.hx
std/neko/_std/sys/ssl/Digest.hx
std/neko/_std/sys/ssl/Key.hx
std/neko/_std/sys/ssl/Socket.hx
tests/unit/src/unitstd/Ssl.unit.hx

- Replaces all the `neko.Lib.load("ssl",..)` by `neko.Lib.loadLazy`.
- Adds a `#if !no_ssl` in haxe.Http that can be used in cpp to avoid depency to sys.ssl.*
- Adds unit tests for Digest, Key and Certificate. I will try to add a small client/server test later.

SSL loadLazy neko 

---

std/cpp/_std/sys/net/Socket.hx
std/cpp/_std/sys/ssl/Socket.hx

I left a typo in my last minute changes of yesterday. 
This should fix hxcpp CI tests.
The error on haxe CI cpp tests will be fixed by a PR on hxcpp.

Fix cpp sys.net.Socket

---

src/generators/genphp.ml
std/php/Boot.hx
tests/unit/src/unit/issues/Issue4973.hx

make HExceptions with an error code != null catchable, i.e. HExceptions from _hx_error_handler
remove duplicated error message, filename and line in HException from  _hx_error_handler

Small modifications to PHP exception/error handling

---

std/lua/_std/haxe/Utf8.hx
tests/unit/src/unitstd/haxe/Utf8.unit.hx

This fix is based on decode_code_point of [unifill/Utf8.hx](https://github.com/mandel59/unifill/blob/master/unifill/Utf8.hx)

[lua] Fix haxe.Utf8.iter, charCodeAt and validate

---

std/cpp/_std/Sys.hx

hxcpp has a println function, so there is no need to double call "print"

Use __hxcpp_println

---

src/generators/gencpp.ml
src/syntax/ast.ml
src/typing/common.ml

Right now, the following code will generate an endless loop in hxcpp:
```haxe
class Main {
var t:Test = 1;
t++;
trace(t);
}
}
@:coreType abstract Test from Int to Int {}
```
Adding new `@:coreType` abstracts is useful so libraries can add their own types that aren't officially supported by hxcpp, like `IntPtr`. After some discussion with Hugh, it was settled that a new metadata, `@:scalar` would be used to denote these types. So with this patch, the following program will compile and work correctly:
```haxe
class Main {
var t:Test = 1;
t++;
trace(t);
}
}
@:include("../../test.h")
@:scalar
@:coreType extern abstract Test from Int to Int {}
```
`test.h`:
```c++
typedef int Test;
```

[cpp] Fix @:coreType abstracts handling, and add @:scalar

---

src/main.ml

This PR adds support for `--wait stdio` argument which makes haxe completion server use stdin and stderr instead of sockets for communication.
This solves a number of annoying problems for IDE, for example:
* multiple instances of an IDE don't need to somehow determine a free port to use for a new haxe server
* we don't need to care about other programs already listening to the port we'd like to use for haxe
* when starting haxe server as a subprocess, we don't need to wait/retry connecting to the server and can invoke queries right away without any race conditions (e.g. https://github.com/nadako/haxe-languageserver/issues/7)
The protocol is the following:
* everything is binary
* ide sends queries to stdin, haxe replies to stderr
* ide and haxe exchange messages consiting of two parts: …

add --wait stdio

---

std/lua/_std/EReg.hx
std/lua/lib/lrexlib/Rex.hx

This PR adds support for UTF-8 mode (`u` flag) to EReg on Lua, as in Neko, C++ and PHP.

[lua] Support UTF-8 mode in EReg

---

std/haxe/io/Input.hx

Here's the fix for haxe.io.Input I talked about earlier.  I'm opening as a pull request since it involves some of the core types that are extended by most of the targets.  I wanted to have a few more eyes on it before I pulled the trigger.
The travis CI build for this branch is clean:
https://travis-ci.org/HaxeFoundation/haxe/builds/131537312

fix the base haxe.io.Input class for reading bytes

---

std/haxe/macro/Expr.hx

They need two asterisks  
http://api.haxe.org/haxe/macro/Constant.html

fix haxe.maco.Constant value documentation

---

std/haxe/EntryPoint.hx

The current implementation with `process.nextTick()` blocks all I/O events, as described in the Node.js documentation :
> Note: the next tick queue is completely drained on each pass of the event loop before additional I/O is processed. As a result, recursively setting nextTick callbacks will block any I/O from happening, just like a while(true); loop.
With `setImmediate(run)` the function is called after I/O events callbacks.

Fix haxe.EntryPoint on Node.js

---

std/haxe/EntryPoint.hx

I made my previous pull request (https://github.com/HaxeFoundation/haxe/pull/5413) too quickly.
After watching the sys implementation I did some additional corrections:
- The run loop must stop if the nextTick returned by processEvents is less than zero.
- We can use this nextTick with setTimeout and avoid useless calls of run()

More fixes on Node.js EntryPoint

---

std/DateTools.hx

Small examples to demonstrate how the syntax should look like.

DateTools.format examples

---

std/sys/db/RecordMacros.hx

Take id field by name 'id' in case we don't have meta or type based field.
Example:
```haxe
@:table("handle")
@:id(ROWID)
class SomeHandle extends sys.db.Object
{
public var ROWID : SUId;
public var id : SText;
public var country : SNull<SText>;
public var service : SText;
public var uncanonicalized_id : SNull<SText>;
public static var manager = new sys.db.Manager<SomeHandle>(SomeHandle);
}
```

Multiple table id declaration

---

std/haxe/ds/Vector.hx
tests/unit/src/unitstd/haxe/ds/Vector.unit.hx

In neko, cpp, cs and java copying takes place as if an intermediate buffer is used, allowing the destination and source to overlap if src and dest point to the same vector. So for all remaining targets the blit code should be adjusted.
Example:
var v = new haxe.ds.Vector<Int>(10);
for (i in 0...10) v.set(i, i); //[0,1,2,3,4,5,6,7,8,9]
haxe.ds.Vector.blit(v, 0, v, 1, 9);
trace(v); //outputs [0,0,0,0,0,0,0,0,0,0] but should be [0,0,1,2,3,4,5,6,7,8]

fix vector blit

---

src/generators/genphp.ml
tests/unit/src/unit/issues/Issue5470.hx

[php] Use `property_exists` instead of `isset` when checking function fields

---

src/optimization/dce.ml

@nadako  here's the adjustments I could find for lua.  It looks like it's ok to drop the Array and String class definitions.  I can't think of a reason why they need to always be present unless they're used... unless we want to provide a lot of dynamic run time safety for methods.  Maybe this could be a compiler flag?
FWIW, this drops the minimal "hello world" generated output from ~2500 bytes to ~1100.

[lua] dce adjustments for lua

---

src/generators/gencpp.ml
tests/unit/src/scripthost/Issue5351.hx
tests/unit/src/unit/issues/Issue5351.hx

Currently, the __scriptableFunctions array is being filled with functions
from all base classes. This not only makes the vtable grow very big,
but also confuses the vtable numbering in such a way that it is possible
to override a wrong function.
The changed test failed in multiple different ways because of that.

[cppia] Do not generate __scriptableFunctions from parent classes

---

std/cpp/cppia/HostClasses.hx

`IntIterator` doesn't contain any code that would not allow it to be compiled in cppia. And if it is excluded, Haxe compilation may fail on subsequent times if the compilation server is on, due to the fact that `IntIterator` has an inline constructor.

[cppia] Do not exclude IntIterator

---

src/generators/codegen.ml
src/generators/genpy.ml
src/macro/interp.ml
src/optimization/analyzer.ml
src/optimization/analyzerTexpr.ml
src/optimization/analyzerTypes.ml
src/typing/matcher.ml
src/typing/type.ml

This makes the output from `dump=pretty` almost indistuingishable from regular Haxe code. While of course being a lot more readable, this also has the nice side effect of working nicely with Haxe syntax highlighting.
Some things that were not printed previously are now printed, like metas on type declarations and fields, or from and tos of abstracts.
Some comparisons:
[FlxSprite.dump **now**](https://gist.github.com/Gama11/628253dc8d21f643554186c2051f37f8)
[FlxSprite.dump before](https://gist.github.com/Gama11/cdec54857a6eca9254a8b82b9f319012)
[hscript.Expr.dump **now**](https://gist.github.com/Gama11/6139ff28577f5a76961a133675155480)
[hscript.Expr.dump before](https://gist.github.com/Gama11/07f705b0c561c75bc52e21a280a32558)

Make dump=pretty look more like Haxe code

---

tests/README.md

This actually makes it clickable in VSCode's markdown preview.

tests/README.md: format /unit.html as a link

---

tests/README.md

HXCPP_NO_DEBUG_LINK does not speed up run times.

tests/README.md: run times -> compilation times

---

src/generators/codegen.ml

closes #5573
Looks ok to me now, example from `Sys.dump`:

-D dump: fix variable init expression printing

---

src/generators/gencommon.ml
src/generators/gencs.ml
src/generators/genjava.ml
std/cs/internal/FieldLookup.hx
tests/unit/src/unit/issues/Issue5572.hx

this makes DynamicObject implementation class look like this (reduced for readability):
```cs
public class DynamicObject : global::haxe.lang.HxObject {
public global::haxe.lang.FieldHashConflict __hx_conflicts;
public int[] __hx_hashes;
public object[] __hx_dynamics;
public int[] __hx_hashes_f;
public double[] __hx_dynamics_f;
public int __hx_length;
public int __hx_length_f;
public override bool __hx_deleteField(string field, int hash) {
if (( hash < 0 )) {
return global::haxe.lang.FieldLookup.deleteHashConflict(ref this.__hx_conflicts, hash, field);
}
// [ snip previous implementation ]
return false;
}
public override object __hx_lookupField(string field, int hash, bool throwErrors, bool isCheck) {
if (( hash < 0 )) {
global::haxe.lang.FieldHashConflict conflict = …
```

[cs] support field name hash collisions in dynamic objects (closes #5572)

---

src/generators/codegen.ml

-D dump: don't print inline vars as (inline,never) properties

---

src/display/display.ml
src/main.ml
src/typing/common.ml
tests/display/src/DisplayTestContext.hx
tests/misc/projects/Issue1968/compile.hxml.stderr
tests/misc/projects/Issue2991/compile.hxml.stderr
tests/misc/projects/Issue2993/compile.hxml.stderr
tests/misc/projects/Issue2995/position.hxml.stderr
tests/misc/projects/Issue2995/usage.hxml.stderr
tests/misc/projects/Issue2996/compile1.hxml.stderr
tests/misc/projects/Issue2996/compile2.hxml.stderr
tests/misc/projects/Issue2997/compile1.hxml.stderr
tests/misc/projects/Issue5123/compile.hxml.stderr
tests/misc/src/Main.hx

this moves (almost all) display printing functions from `main.ml` into `display.ml`
also it factors out `Parser.TypePath` handling into functions for better maintainability
and finally it makes `Common.get_real_path` consistently return absolute path with proper name case
oh, and it makes `@position` completion use `get_real_path` so IDEs on windows won't try to open a lowercased file
just making a PR for easy squash+merge and additional Travis testing.

[display] some refactorings + get_real_path changes

---

std/haxe/macro/Printer.hx

```hx
import haxe.macro.Expr.FieldType;
import haxe.macro.Expr.TypeDefKind;
import haxe.macro.Printer;
class Main 
{
var result = new Printer().printTypeDefinition(
{
pack : [],
name : "Sample",
params: [],
pos : null,
kind : TypeDefKind.TDAbstract(macro:String),
fields : [
{
name: "new",
kind: FieldType.FFun(
{
args: [],
ret: null,
expr: (macro this = ""),
}
),
pos : null,
}
],
}
);
trace(result);
}
}
```
I expected: 
```hx
abstract Sample(String) {
function new() this = "";
}
```
but acutal:
```hx
abstract Sample(String) {
function new() this = ""
}
```
This abstract causes "Missing ;" compile error.

haxe.macro.Printer misses a semicolon at the method of abstract types.

---

src/context/common.ml
src/generators/gencommon.ml
src/macro/interp.ml
src/path.ml
src/server.ml
src/typing/type.ml
src/typing/typecore.ml
src/typing/typeload.ml
src/typing/typer.ml
std/haxe/macro/CompilationServer.hx

This adds a (currently small) API to interact with the compilation server. Right now we only support setting module caching policies and clearing files.
I acknowledge that it's possible to shoot yourself in the foot with this, but it's not really intended for the typical Haxe end-user anyway. The main focus here is IDEs and haxelib.
I'm testing this in an empty HaxeFlixel project. This is the compilation --times output without any flags:
```
name            | time(s) |   % |     # | info
-----------------------------------------
analyzer        |   0.479 |  23 | 49230 | 
filters         |   0.414 |  20 |     1 | 
generate        |   0.207 |  10 |     1 | 
swf           |   0.207 |  10 |     1 | 
macro           |   0.125 |   6 |   183 | 
other           |   0.163 |   8 |     1 | 
parsing …
```

add haxe.macro.CompilationServer

---

src/context/common.ml
src/display/display.ml
src/display/displayOutput.ml

Right now, when typing something with `null`, vshaxe will suggest `Null` instead:
This is mildly annoying - if you press enter, you end up with incorrect code. The simple fix is to provide `null` in toplevel completion as well, providing an exact match.
The same is true for `true` and `false`.
This is a pretty common approach, `null`, `false` and `true` are all suggested by FD's auto-comletion for instance.

[display] add null, false and true to toplevel completion

---

std/cpp/Pointer.hx

Fixes an issue where the variable used in Pointer.addressOf gets value-inlined in the call.
```haxe
class Test {
public static function main () {
var i = 0;
trace(cpp.Pointer.addressOf(i).get_raw());
}
}
```
```
./src/Test.cpp: In static member function ‘static void Test_obj::main()’:
./src/Test.cpp:29:67: error: no matching function for call to ‘cpp::Pointer_obj::addressOf(int)’
HXDLIN(   4)  int* _hx_tmp1 = ::cpp::Pointer_obj::addressOf((int)0)->get_raw();
^
./src/Test.cpp:29:67: note: candidate is:
In file included from /home/ibilon/Code/Haxe/libs/hxcpp/include/hxcpp.h:336:0:
/home/ibilon/Code/Haxe/libs/hxcpp/include/cpp/Pointer.h:514:27: note: static cpp::Pointer<T> cpp::Pointer_obj::addressOf(T&) [with T = int]
inline static Pointer<T> addressOf(T &value)  { return …
```

Require Pointer.addressOf to take a variable as argument

---

src/generators/genjs.ml
tests/optimization/src/issues/Issue5477.hx

The ternary always seems to generate without spaces while the rest generates spaces around anything. This should add spaces around the `?` and `:`.

[js] generate ternary operator with spaces

---

src/generators/genas3.ml

See: http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Number.html
Current output is: Math["POSITIVE_INFINITY"], which is undefined, and when assigned to a Number, results in NaN. Number["POSITIVE_INFINITY"] works.
Testcase:
```
class Test
{
var inf:Float = Math.POSITIVE_INFINITY;
trace("inf is: "+inf);
}
}
```
Compiles to:
```
package  {
import haxe.Log;
public class Test {
static public function main() : void {
var inf : Number = Math["POSITIVE_INFINITY"];
(haxe.Log._trace)("inf is: " + inf,{ fileName : "Test.hx", lineNumber : 7, className : "Test", methodName : "main"});
}
}
}
```
And (slightly modified for textfield):
Fixed:

Positive / negative infinity are members of the Number class in AS3

---

extra/release-checklist.txt

Small precisions on the path of the markdown files and the requirement on git-lfs.
https://git-lfs.github.com/

Small update of release steps with new haxe.org code

---

src/typing/typeload.ml

If user defines any modules in `php` package then compiler cannot find them, because we expect all such modules to be located in `php7` directory.
This PR makes compiler to look into `php` directory if module is not found in `php7`.

User-defined modules in renamed packages (fixes #5921)

---

std/Math.hx

Hello,
I noticed this typo in the documentation. 
Cheers

Fixed typo in documentation of POSITIVE_INFINITY

---

std/php7/Resource.hx

`sys.io.File has no field or subtype FileHandle`

[php7] Remove filehandle import in resource

---

src/generators/genjs.ml

This fixes a missing separator in the .__properties__ attribute.
Generated code used to be like this:
```
format_swf__$SWFData_SWFData_$Impl_$.__name__ = ["format","swf","_SWFData","SWFData_Impl_"];
format_swf__$SWFData_SWFData_$Impl_$.__properties__ = {set_length:"set_length",get_length:"get_length"}
format_swf__$SWFData_SWFData_$Impl_$._new = function() {
```
Now is like this:
```
format_swf__$SWFData_SWFData_$Impl_$.__name__ = ["format","swf","_SWFData","SWFData_Impl_"];
format_swf__$SWFData_SWFData_$Impl_$.__properties__ = {set_length:"set_length",get_length:"get_length"};
format_swf__$SWFData_SWFData_$Impl_$._new = function() {
```
Notice the ; after the } of properties.

Fixed missing separator after __properties__

---

std/php7/_std/sys/db/Mysql.hx
tests/unit/src/unit/MySpodClass.hx
tests/unit/src/unit/TestSpod.hx

Using the mysql resultset in a simple for loop caused everything to hang for me. The `hasNext` method checks if `fetchedRow` is not `null` but it seems `fetchedRow` is never cleared. I assume that's what the `withdrawFetched` method is for, but wasn't actually implemented.

[php7] Actually withdraw fetched row

---

src/generators/genphp7.ml
tests/sys/src/io/TestFileInput.hx

When trying to use FileInput.readBytes with php7, I get a PHP error: `Trying to get property of non-object in out/lib/sys/io/FileInput.php:xx`, pointing to the line containing `$r1 = $r->length;` which tries to access field `length` of a php string instance, instead of using `strlen`.
Initially I tried to fix it in `std`, but that didn't feel like it's the correct place. So I went and modified the generator code instead (with the hope and risk of affecting more than just that one usecase). 
I am not an ocaml expert and I am not sure, if my patch is corect or if it should completely replace the pattern prio to it, or if it needs additional treatment. So please let me know what corrections I should make.

[php7] use strlen for strings in FileInput.readBytes

---

std/php7/_std/sys/db/Mysql.hx

PHP ends up in a recursive loop when trying to close a Mysql connection.

[php7] fix recursive call in MysqlConnection.close

---

std/haxe/io/Path.hx

While working with the file system @back2dos was right to suggest this change. More infos here: https://groups.google.com/forum/#!topic/haxelang/aP4fQWiEmD4

UNC paths are absolute paths as well

---

src/optimization/optimizer.ml

Fixes #6034 by making a third pass on the result of the inline constructors optimization filter which checks if there are any inline constructors left in the output.

Fix fail to inline extern constructor not producing an error #6034

---

std/java/Lib.hx

Recursion. See also: recursion.

java.Lib: remove confusing deprecated docs

---

src/optimization/optimizer.ml
tests/optimization/src/issues/Issue6093.hx
tests/unit/src/unit/issues/Issue6093.hx

I created a type_inline_ctor function that will add the field inits of the passed class to the function body before calling type_inline again.
type_inline calls this function in the TCall super case instead of directly recursing.
The constructor inliner code then calls this function instead of adding the field inits there.

Fix inline constructor field initialization for super constructors. #6093

---

std/haxe/EnumFlags.hx
tests/unit/src/unit/TestSpecification.hx
tests/unit/src/unitstd/haxe/EnumFlags.unit.hx

Fixes haxe.EnumFlags.unset() for enum indexes 28 to 31.

Fix EnumFlags.unset

---

src/context/meta.ml
src/generators/genjs.ml
src/optimization/filters.ml

I ported the `SwitchBreakSynf` from `gencommon.ml` to a simplier filter that detects loop `break`s inside `switch` and label them and their loops with a `TMeta` intended to be used in a target generator.
Then I added usage of these labels in `genjs.ml` to generate labeled loops and breaks instead of try-catches (see #3883).
I also tried to remove the `SwitchBreakSynf` from `gencommon.ml` and use the metadata directly in `gencs.ml` (to generate `goto`) and `genjava.ml` (to generate the same as js), but turns out it's not that easy since `gencommon.ml` filters out `TMeta`s and even if I whitelist the new one, it still doesn't work properly, so this requires more research.
Anyway, this PR is more a first try of extracting and simplifying bits of `gencommon.ml`. I don't really expect it to be …

add switch-break labeling and use it for generating better js

---

std/js/Browser.hx

Closes #6050
If you are browsing private on iOS, localstorage is available but you cannot write in it. It'll throw "QUOTA_EXCEEDED_ERR: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota."
This can be solved in the detection of localstorage by trying to write something in storage.

update getLocalStorage/getSessionStorage check

---

src/generators/gencommon.ml
src/generators/gencs.ml
std/cs/_std/Type.hx
std/cs/internal/HxObject.hx

This introduces a new gencommon filter that transforms enums to classes in a more effecient and properly typed way. It's also better for C# interoperability since on C# side one can `as`-cast the instance and access its values.
Example:
```haxe
enum E {
A;
B(e:E);
C(v:Int, s:String);
}
class Main {
f(B(C(1, "hi")));
}
static function f(e:E) {
switch (e) {
case A:
case B(C(i, s)):
default:
}
}
}
```
Generates the following (reformatted for brevity). This is similar to what F# compiler does for ADT, except that they do typechecks instead of switching on `index`, support type parameters (no GADT) and tempvar the downcasted instance if there are more than one captured var - something we might want to improve in future.
```cs
public class E : global::haxe.lang.Enum { …
```

[cs] rework enum-to-class generation

---

.travis.yml
Makefile
Makefile.win
appveyor.yml

This PR changes the build process to use ocamlfind and cleans up the Makefile some more. Currently, the only libraries we use are str and unix from the OCaml distribution, but there may be more in the future. We can also look into replacing some of the extlib libraries (objsize, pcre, xml-light, ziplib... maybe even extlib if someone is brave enough to look into that) at some point.
Obviously, this makes ocamlfind a build dependency.
CI is failing because lua.org is down.

Use Ocamlfind

---

src/generators/gencommon/closuresToClass.ml
src/generators/gencommon/reflectionCFs.ml
src/generators/gencs.ml
src/generators/genjava.ml
std/cs/_std/Reflect.hx
std/cs/_std/Type.hx
std/cs/internal/Function.hx
std/cs/internal/Runtime.hx
std/cs/internal/StringExt.hx
std/java/_std/Reflect.hx
std/java/_std/Type.hx
std/java/internal/Function.hx
std/java/internal/Runtime.hx
std/java/internal/StringExt.hx

This makes invokeDynamic/invokeField and friends take native arrays instead of Haxe arrays. This avoids unnecessary haxe Array allocation in many cases such as dynamic calls through structure types or method closures.
Hope I didn't mess it up. tests seem to pass for me, will merge after Travis greenlight.

[cs/java] use native arrays for dynamic function invokation

---

src/generators/codegen.ml
src/generators/gencommon.ml
src/generators/gencommon/switchToIf.ml
src/generators/gencommon/tryCatchWrapper.ml
src/generators/gencs.ml
src/generators/genjava.ml
src/optimization/filters.ml
std/cs/Lib.hx

This moves the `TryCatchWrapper` transform used in C#/Java targets into first-pass filters, so it's run before analyzer and DCE, resulting in much cleaner output. Obviously the filter now also doesn't depend on anything from gencommon and potentially can be easily re-used for other targets (I'm thinking about reworking the current JS hackery to it). This also means that c#/java/gencommon filters shouldn't add `TThrow`s of types that are not target-specific exception subclass, but there are only a couple places that I already changed it in `development`.
It needs some cleanup, but it passes all the tests for me, so I'm gonna merge it when Travis is green.

[cs/java] run TryCatchWrapper as a normal filter before analyzer/dce

---

src/context/common.ml
src/generators/gencommon.ml
src/generators/gencommon/defaultArguments.ml
src/generators/gencommon/fixOverrides.ml
src/generators/gencs.ml
src/generators/genjava.ml
src/optimization/filters.ml

Run the gencommon's `DefaultArguments` filter by filters.ml in the pre-analyzer pass, which makes output nicer in some cases (thanks to local DCE and expression fusion).
As a side-effect it's now also run before `rename_local_vars`, meaning that it can reuse the argument name for the var without worrying about name clases, so it doesn't have to generate those ugly `__temp_arg1` names.
The `SetHXGen` is also run by filters.ml now, since `DefaultArguments` checks for meta added by that filter.
Will merge on Travis greenlight.
> PS The `DefaultArguments` is actually a normal expression filter, but it needs some refactoring to be used as one, so I'm running it in PASS 1.5 right now.

[cs/java] extract DefaultArguments from gencommon into PASS 1.5 filters

---

std/cs/_std/Type.hx
std/java/_std/Type.hx
std/js/_std/Std.hx
std/lua/_lua/_hx_classes.lua
tests/unit/src/unit/TestReflect.hx

This removes a specification for `Type.getEnumName(Bool)` and `Type.resolveEnum("Bool")` and some of related implementations (see linked issues).
We should review and most probably remove other weird specifications such as `getClassName`/`resolveClass` for `Class`, `Enum`, `Float`, `Int`, `Dynamic` and other standard abstracts.

Don't require Bool to be an enum (closes #5804, closes #4120)

---

std/haxe/macro/Printer.hx

Currently:
```haxe
class Main {
Macro.print('012345\r\n6789');
}
}
class Macro {
public static macro function print(e:haxe.macro.Expr) {
var s = new haxe.macro.Printer().printExpr(e);
return macro Sys.println($v{s});
}
}
```
generates:
```js
process.stdout.write("'012345\r\\n6789'");
// what you see in the terminal: \n6789'
```
after fix:
```js
process.stdout.write("'012345\\r\\n6789'");
// what you see in the terminal: '012345\r\n6789'
```

Escape \r as well

---

src/macro/macroApi.ml
src/macro/macroContext.ml
std/haxe/macro/Context.hx

This PR adds a second optional argument to `Context.defineType` which allows explicitly controlling module dependency for the newly-created module. If specified, it will be used as a dependency instead of the current module when defining a module for the new type.
This is useful when we define a new type, derived from some existing one from another module, like in a `@:genericBuild Const<T>` macro used in our codebase (it generates "readonly" version of typedef'd structure types). In cases like this it doesn't make sense for a newly created module to depend on the module where the macro was called from (the "current" one) and instead it should depend on a module where the original type is defined.
The current behaviour screws cache server pretty bad in our large codebase, so completion …

[macro] support explicit module dependency for Context.defineType (closes #5613)

---

extra/CHANGES.txt
std/EReg.hx
std/cpp/_std/EReg.hx
std/cs/_std/EReg.hx
std/flash/_std/EReg.hx
std/hl/_std/EReg.hx
std/java/_std/EReg.hx
std/js/_std/EReg.hx
std/lua/_std/EReg.hx
std/neko/_std/EReg.hx
std/php/_std/EReg.hx
std/php7/Global.hx
std/php7/_std/EReg.hx
std/python/_std/EReg.hx
std/python/lib/Re.hx
tests/unit/src/unitstd/EReg.unit.hx

I need this from time to time and I think it should be in the std lib. I tried to use platform-native (or recommended) regex escaping functions, but for others (cpp,neko,hl,lua) I used the implementation involving `map`. It works but it may not be the most efficient solution which can be improved in future.
I know we're in feature freeze, but this addition seems to be very minor and safe for 3.3.

add EReg.escape

---

std/haxe/io/Bytes.hx

Current implementation of `Bytes.toString()` returns a string from the first byte to the last or tol the first null-byte. While e.g. on JS it always return from the first byte to the last byte.
This PR makes Flash implementation behave the same way with JS one.

[flash] `haxe.io.Bytes.toString()` stops on zero-byte

---

src/context/common.ml
src/context/meta.ml
src/optimization/filters.ml
src/optimization/inlineConstructors.ml
src/optimization/optimizer.ml
tests/optimization/src/Test.hx
tests/optimization/src/TestJs.hx

This is a rework of the inline constructors filter which adds support for inlining in multiple new cases.
``` haxe
var a = { x : ["foo", "bar"], y : 0.5, z : new Point(0,0) };
a.x[0] = "modified";
a.y = 1.5;
trace( a.x[0] + a.x[1] + a.y + a.z.y );
```
This compiles to (JS target):
``` javascript
var a_z_y;
var a_z_x;
var a_y;
var a_x_1;
var a_x_0 = "foo";
a_x_1 = "bar";
a_y = 0.5;
a_z_x = 0;
a_z_y = 0;
a_x_0 = "modified";
a_y = 1.5;
console.log(a_x_0 + a_x_1 + a_y + a_z_y);
```
And collapses into just `console.log("modified" + "bar" + 1.5 + 0);` with analyzer-optimize on.
If a variable is aliasing an inlined object, assigning it to another variable makes that other variable also an alias.
``` haxe
var a = [0, 1, 2];
var b = a;
var c = { x : b, y : "test" };
trace(b[0] + a[1] + c.x[2]); …
```

Inline constructors rework

---

std/haxe/crypto/Sha224.hx
std/haxe/crypto/Sha256.hx

Forced Inline (@:extern) on heavily used internal micro-functions in SHA 224 and 256. Tested against as3 target only.
Inlined code is still not very large, and should have minimal exe bloat tradeoff for a very large speed increase.

* 4x speed Optimization Sha224.hx, Sha256.hx via forced inlining

---

src/optimization/inlineConstructors.ml
tests/optimization/src/issues/Issue6229.hx

The reworked constructor inliner was already unwrapping blocks inserted by constructor inlining, this change will make it also unwrap any nested block inside of an unwrapped block.
This should fix #6229

Flatten blocks in inline constructors. Fixes #6229

---

src/optimization/inlineConstructors.ml

When there are multiple aliasing variables this change will give priority to names of variables that are user created. (By finding variables that have the UserVariable metadata)
This improves the situation described by nadako here: https://github.com/HaxeFoundation/haxe/pull/6230#issuecomment-298713427

Improve variable names in inline constructors rework.

---

tests/unit/src/unit/issues/Issue6135.hx
tests/unit/src/unit/issues/Issue6169.hx

I tried the tests individually with the old inline constructors to confirm they fail.
The test for #6135 fails on static typed platforms only.

Tests for #6135 and #6169

---

.travis.yml
appveyor.yml
tests/Indexer.hx
tests/RunCi.hx

This is the initial implementation to use both Travis and AppVeyor to submit the builds to the nightly builds s3 repo. We still need to build windows-installer and mac-installer (and Linux 32-bit will be discontinued), but I think this initial implementation can already be merged (as a flattened commit ;) )
Closes #6149

Upload nightly builds through Travis/AppVeyor

---

src/compiler/server.ml

This confuses vshaxe completion, escpecially since the output format is also JSON.

Fix compilation-server-test output always being enabled

---

tests/server/src/HaxeServerTestCase.hx

(#6271 caused the compilation server tests to fail)

Add -D compilation-server-test in the right place

---

std/cs/_std/sys/io/File.hx
std/lua/_std/sys/io/File.hx
tests/sys/src/ExitCode.hx
tests/sys/src/Main.hx
tests/sys/src/io/TestFile.hx

Basically, I just changed it to use the overload of `File.Copy()` with an `overwrite` parameter:
https://msdn.microsoft.com/en-us/library/9706cfs5(v=vs.110).aspx

[cs/lua] overwrite contents in File.copy(), closes #6278

---

std/java/_std/sys/FileSystem.hx
std/php7/_std/sys/FileSystem.hx
tests/sys/src/TestFileSystem.hx

Simply check whether there's already a directory with the same name to avoid the exception.

[java/php7] fix FileSystem.createDirectory() for dirs that exist, closes #6268

---

std/flash/_std/haxe/ds/ObjectMap.hx
std/flash/_std/haxe/ds/WeakMap.hx

Error when targeting as3. Generates NativePropertyIterator.as and NativeValueIterator.as but __foreach__ __forin__ missing.  Better to not generate at all, since those impl are not used.
Minor issue that is solved by not generating the above classes, and therefore bypassing any missing function dependencies.
Note that no test can be written because of differences in developer as3 compilation context. This error was detected during use of the generated as3 code in a FlashBuilder environment where the haxe-generated as3 code was included as an additional source directory.

AS3 target Compile error with missing iterators.

---

src/generators/gencommon/enumToClass2.ml
std/cs/_std/Type.hx
std/cs/internal/HxObject.hx
tests/unit/src/unit/issues/Issue6299.hx

I modified something in gencommon so I'm not sure if I need to modify something for java too.

Fix enum with argument named index, closes #6299

---

std/lua/_std/sys/FileSystem.hx

Goal is to hide [this](http://api.haxe.org/sys/LFileSystem.html) confusing typedef from the API docs.
(I hope) It is only used in this class.

[lua] `sys.LFileSystem` as import, not as typedef

---

.travis.yml
tests/RunCi.hx
tests/misc/cppObjc/build.hxml
tests/sys/compile-each.hxml
tests/unit/compile-cppia-host.hxml
tests/unit/compile-each.hxml

this PR enabled caching for some folders during the build process, the following folders are cached and reused between builds
- .opam - opam files
- neko - the neko folder including compiled files
- apt-cache - downloaded apt-get files (linux)
- hxcache - hxcpp cache
- _hxbuild - the compiler _build folder
- lua_env - lua files
- .luarocks - .luarocks folder (@jdonaldson please check)
- Library/Caches/Homebrew - downloaded homebrew files (osx)
Although it is not recommended to cache apt-get or homebrew files, it seems to make a difference in my tests.
Sorry for the stupid commits, but it's hard to test travis files ;)

Travis cache

---

std/php7/_std/sys/db/Mysql.hx

passes on the error message of MySQL when throwing exceptions, so devs can see why their query failed

[php7] add native mysqli error message when throwing an exception

---

src/macro/macroApi.ml
src/syntax/ast.ml
src/syntax/parser.mly
src/typing/typeload.ml
std/haxe/macro/Expr.hx
std/haxe/macro/Printer.hx
tests/unit/src/unit/HelperMacros.hx
tests/unit/src/unit/issues/Issue2958.hx
tests/unit/src/unit/issues/Issue4799.hx

This PR adds support for specifying argument names in a function type with the following syntax:
```haxe
arg1:Type1 -> arg2:Type2 -> Ret
```
This syntax is the most obvious choice as people are already familiar with it because Haxe prints function type with argument names like that.
The parsing part is super-easy and the change is tiny: we parse an identifier, then check if it's followed by a colon (`:`), then we parse a named argument, otherwise we continue parsing as a type path.
The AST representation takes the same approach as optional args: we add a `CTNamed` variant next to `CTOptional` and handle it similarly.
The typing part is the smallest change: when we loop through `CTFunction` arguments, we filter out `CTNamed` and extract name from it (again, similar to how we extract …

support argument names in function type (closes #4799)

---

src/display/display.ml
src/generators/gencommon/dynamicOperators.ml
src/generators/gencpp.ml
src/generators/genhl.ml
src/generators/genpy.ml
src/generators/genswf9.ml
src/macro/eval/evalJit.ml
src/macro/macroApi.ml
src/optimization/analyzerTexpr.ml
src/optimization/analyzerTexprTransformer.ml
src/optimization/optimizer.ml
src/syntax/ast.ml
src/syntax/parser.mly
src/typing/type.ml
src/typing/typer.ml
std/haxe/macro/Expr.hx
std/haxe/macro/ExprTools.hx
std/haxe/macro/Printer.hx
tests/optimization/src/TestAnalyzer.hx
tests/unit/src/unit/TestMatch.hx
tests/unit/src/unit/UnitBuilder.hx
tests/unit/src/unit/issues/Issue6224.hx

Since @Simn said "sounds good" to this, I'm preparing this PR :-P
This removes the `EIn` expression kind and instead adds `OpIn` binary operator (adapting other code accordingly).
I believe this makes sense because `in` is basically _is_ a binary operator, and even though in basic Haxe it's only used in `for` expressions, `in` often processed as a binop by macros.
This is obviously a macro breaking change, so consistency alone wouldn't be enough to make it. Having `in` as a binop also makes it automatically overloadable by abstracts through the `@:op` metadata, which is a nice feature for building DSLs. See #6224 for more info (also see test case included in this PR for an example).

make `in` a Binop and remove `EIn` (closes #6224)

---

src/context/meta.ml

Probably used to be `Platforms [Php;Php7]` or something like that, but now it looks a bit silly. :)

Fix duplicated platform in @:phpGlobal docs

---

std/haxe/macro/Compiler.hx

`haxe.macro.Compiler.includeFile("test.lua", "inline");` made `__js__` appear in the Lua output, leading to a rather funny error:
```
attempt to call global '__js__' (a nil value)
```

[lua] fix Compiler.includeFile() with position = Inline

---

.vscode/settings.json

It's common practice to commit .vscode settings (eventually, it might be good to have a tasks.json and a launch.json too).
The first two are necessary to work with the vscode-ocaml extension. The files.exclude pattern prevents always ending up in _build files instead of the actual source files by accident (for instance via Ctrl+P, which used to show both).
Note that F1 -> Clear Editor History might be necessary for Ctrl+P not to show _build files anymore since it shows recently opened files regardless of the files.exclude setting.
[skip ci]

Add a VSCode settings.json

---

std/haxe/Int64Helper.hx
tests/unit/src/unit/issues/Issue5493.hx

Parsing a negative number ending in a zero (ie `"-20"`) would result in a "Conversion underflow" error (as 0 fails the `Int64.isNeg()` check)

fixed: Int64Helper.parseString would error on negative numbers ending in a zero

---

extra/CHANGES.txt
src/generators/genjs.ml
tests/unit/src/unit/issues/Issue6637.hx

See #6637 
Created a PR to check CI.

[js] fixed js syntax on `value.iterator--` (fixes #6637)

---

src/generators/genjs.ml

This makes genjs generate more efficient code for `x.iterator()` calls, which is a much more common case than just getting `x.iterator`, because it's used for iteration:
```haxe
class Main {
for (v in ([1,2,3] : Iterable<Int>)) {
trace(v);
}
}
}
```
BEFORE:
```js
Test.main = function() {
var v = $iterator([1,2,3])();
while(v.hasNext()) console.log(v.next());
};
function $iterator(o) { if( o instanceof Array ) return function() { return HxOverrides.iter(o); }; return typeof(o.iterator) == 'function' ? $bind(o,o.iterator) : o.iterator; }
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = …
```

[js] generate faster code for `x.iterator()` calls

---

src/core/ast.ml
src/macro/macroApi.ml
src/syntax/grammar.mly
src/syntax/reification.ml
src/typing/typeload.ml
std/haxe/macro/Expr.hx
std/haxe/macro/Printer.hx
tests/unit/src/unit/HelperMacros.hx
tests/unit/src/unit/issues/Issue2958.hx
tests/unit/src/unit/issues/Issue4799.hx

This implements https://github.com/HaxeFoundation/haxe-evolution/pull/23

add new function type syntax (closes #4799)

---

src/generators/gencpp.ml

Fix inconsistency in cpp generation. HXCPP_SCRIPTABLE should be using #ifdef and not #if

Fix cpp compilation with HXCPP_SCRIPTABLE undefined

---

src/filters/filters.ml
src/filters/filtersCommon.ml
src/filters/jsExceptions.ml
src/generators/genjs.ml
std/js/Boot.hx
std/js/Lib.hx
std/js/_std/Reflect.hx
tests/optimization/src/TestJs.hx

This reworks JS exception handling in a pre-analyzer/pre-dce filter that handles wrapping/unwrapping, single-catch + Std.is transformation, rethrowing, haxe.CallStack, etc.
E.g.
```haxe
try {
throw "epuc fial";
} catch (e:String) {
trace(e);
} catch (e:Bool) {
trace(e);
js.Lib.rethrow();
}
```
is now generated as
```js
try {
throw new js__$Boot_HaxeError("epuc fial");
} catch( e ) {
var e1 = (e instanceof js__$Boot_HaxeError) ? e.val : e;
if(typeof(e1) == "string") {
console.log("Main.hx:7:",e1);
} else if(typeof(e1) == "boolean") {
console.log("Main.hx:9:",e1);
throw e;
} else {
throw e;
}
}
```
Let's see what travis has to say about this...

[js] rework exception handling (closes #6458)

---

src/context/typecore.ml
src/core/abstract.ml
tests/unit/src/unit/issues/Issue6751.hx

(also refactor related code a little bit)

when checking for casts between two abstract, check for direct to/from first and then for @:to/@:from field casts (closes #6751)

---

std/sys/Http.hx

This url failed to download without this fix
http://taongafarm-dev.akamaized.net/cdn/fac3901fdc2535ee52855ce1cb4cd554/shared/deploy/speech.mpf
For last chunk `cstr` was `'00000000'`, not `'0'`.

sys.Http: fix chunked encoding handling

---

src/typing/typeload.ml

At the moment, it is possible to compile code with variable that can be never read nor set.
`var useless (never, never) : Int`
I propose to make it raise compilation error in the same way as:
`var forbidden (get, default) : Int`

Forbid (never, never)

---

src/core/type.ml
src/typing/typer.ml
std/haxe/io/BufferInput.hx

Current behavior
```haxe
var a = ['hello'];
$type(a[1000]); // String
trace(a[1000]); //null
```
Behavior of this PR:
```haxe
var a = ['hello'];
$type(a[1000]); // Null<String>
trace(a[1000]); //null
```
This PR adds `Null<>` for array read access on all platforms except `Int`, `Bool`, `Float` on static targets.
In addition to proper typing it also makes possible to check array access for null safety (i'm making a plugin for that).

Type array access on Array<T> as Null<T>

---

src/generators/genjs.ml
src/generators/genphp7.ml
src/generators/genpy.ml
std/haxe/Int32.hx
std/haxe/ds/Vector.hx
std/haxe/io/Bytes.hx
std/js/Browser.hx
std/js/Syntax.hx
std/js/_std/Date.hx
std/js/_std/HxOverrides.hx
std/js/_std/Type.hx
std/php/Boot.hx
std/php/Lib.hx
std/php/Syntax.hx
std/php/_std/Reflect.hx
std/python/Boot.hx
std/python/Syntax.hx
std/python/_std/Type.hx
std/python/_std/sys/net/Socket.hx
std/python/internal/HxOverrides.hx
std/python/internal/Internal.hx
tests/runci/targets/Python.hx
tests/unit/src/unit/TestMain.hx
tests/unit/src/unit/TestPython.hx
tests/unit/src/unit/TestSyntaxModule.hx

Unified some methods in modules:
php.Syntax,
js.Syntax,
python.Syntax
@nadako, please, review js and python related changes

{platform}.Syntax modules

---

src/generators/genjs.ml

`js.Syntax.new_()` was renamed to `construct()` in #6849 without updating the deprecation in genjs. This led to an error like this when `__new__` is used:
Warning : `__new__` is deprecated, use `js.Syntax.new_` instead
Unknown js.Syntax method `new_` with 1 arguments

[js] fix __new__ deprecation

---

src/generators/genpy.ml

Puts Python's main() call in a `if __name__ == '__main__':` block. This is a Python convention to allow importing from a module without executing it.

[python] only run main() when executed directly

---

std/hl/_std/sys/ssl/Certificate.hx
std/hl/_std/sys/ssl/Socket.hx

- Fixed double utf8 to ucs2 conversion in ssl.Certificate.altNames (https://github.com/HaxeFoundation/hashlink/issues/115)
- Added boundary check in ssl.Socket readBytes/writeBytes

HL SSL fixes

---

CONTRIBUTING.md
Makefile

* Ensure debugging information is included when linking
* Add some documentation about how to debug
I've added this since it took me quite a while to figure out how to debug the compiler. If there are better ways to do these things, please say and I'll update it.
I've unconditionally added `-g` to the link step - I could hide this behind a DEBUG/other flag instead. `ocamldebug` complains there is no debug information without this.

Add some debug documentation

---

Makefile
opam
src/macro/eval/evalStdLib.ml

Fixes #6773 
Note that this requires a new opam package (not sure if that may be a problem for Windows, please let me know if I'm missing something).
I used the following sample for a quick bit of benchmarking:
```haxe
class Main {
public static function main() {
var buf = new StringBuf();
for (i in 1...100000) buf.addChar(97);
var s = buf.toString();
var x = haxe.Timer.stamp();
for (i in 1...10) haxe.crypto.Sha1.encode(s);
trace(haxe.Timer.stamp() - x);
}
}
```
The results look good. Before these changes:
```
$ > haxe --interp -main Main.hx
Main.hx:8: 8.20536017417907715
```
After these changes:
```
$ > haxe --interp -main Main.hx
Main.hx:8: 0.00219798088073730469
```

Add an OCaml native SHA1 implementation in macros

---

std/cpp/_std/sys/io/File.hx
std/cs/_std/sys/io/File.hx
std/hl/_std/sys/io/File.hx
std/lua/_std/sys/io/File.hx
std/neko/_std/sys/io/File.hx
std/php/_std/sys/io/File.hx
std/python/_std/sys/io/File.hx
tests/unit/src/unitstd/sys/io/File.unit.hx

On some targets this is the current behavior, but for most `File.update` fails if the file doesn't already exist. As `File.update` is documented to behave similar to `File.append` we should guarantee that the file will be created if it doesn't exist on all targets.

File.update should create file if it doesn't exist

---

src/optimization/dce.ml

The `TBinop(OpEq,_,_)` case is duplicated in the Dce.
It's surprising it even works.

Typo in dce

---

src/typing/typer.ml
tests/unit/src/unit/issues/Issue6836.hx

Fixes https://github.com/HaxeFoundation/haxe/issues/6836. Ternary and if expressions both call `unify_min` to determine their type. For types which are nullable by default (String, classes) `unify_raise` never raises when mixing `Null<T>` and `T` in either order, so whichever comes first in the list wins. Types that are *not* nullable by default such as `Int` don't show this behavior, always returning `Null<Int>`.
This fix is pretty on the nose; maybe there's a more general solution?

Fix inconsistent treatment of Null<T> in unify_min

---

src/typing/typer.ml

I initially forgot the `@:generic` when playing around with const type params and had to scratch my head a bit wondering what I was missing. I think mentioning the need for a @:generic class directly in the error is helpful. :)

[typer] more helpful error for invalid usage of @:const type params

---

src/context/typecore.ml
src/typing/typer.ml
tests/misc/projects/Issue5871/Main.hx
tests/misc/projects/Issue5871/Main2.hx
tests/misc/projects/Issue5871/parent-constructor-fail.hxml
tests/misc/projects/Issue5871/parent-constructor-fail.hxml.stderr
tests/misc/projects/Issue5871/parent-no-constructor-fail.hxml
tests/misc/projects/Issue5871/parent-no-constructor-fail.hxml.stderr
tests/unit/src/unit/issues/Issue5323.hx

Fixes #5871 
A private constructor should only be accessible in the class or its direct descendants.
Found one of these in the tests themselves, so I'm sure people have been relying on this, knowingly or not.

Don't allow sibling class access to private constructor

---

Makefile

any %sedlex.regexp? needs to be preprocessed
to not to fail as Uninterpreted extension 'sedlex.regexp'

preprocess ocaml sources via sedlex.ppx

---

src/typing/calls.ml
tests/unit/src/unit/issues/Issue5255.hx
tests/unit/src/unit/issues/misc/Issue5255Class.hx

Fixes #5255 - this `type_type` is trying to load the underlying type's type path in the context of the calling file, which doesn't resolve in this example. For class fields this line doesn't seem necessary at all.

Fix for generic function through typedef

---

std/haxe/ds/Vector.hx
std/haxe/io/Path.hx
std/haxe/rtti/XmlParser.hx
std/neko/vm/Module.hx

When running the "Haxe: Run Global Diagnostics Check" command in vshaxe, several "unused variable" warnings currently point into standard library files, which is obviously not ideal.

[std] remove some unused variables

---

std/haxe/Log.hx

This empty line is necessary to fix markdown formatting in VSCode hover hints. It seems to work in the API docs, but I don't think this is valid markdown, GitHub's markdown renderer also needs the empty line.
Before:
After:

[std] fix markdown syntax in haxe.Log.trace() docs

---

std/flash/_std/haxe/Json.hx
std/haxe/Json.hx
std/haxe/format/JsonPrinter.hx
std/js/_std/haxe/Json.hx
std/lua/_std/haxe/Json.hx
std/php/_std/haxe/Json.hx
std/python/_std/haxe/Json.hx

This seems like a great use for the new syntax: `Dynamic -> Dynamic -> Dynamic` isn't very helpful at all when reading the code, so you probably have to look up the meaning of the parameters in the doc comment, but `(key:Dynamic, value:Dynamic) -> Dynamic` gives you a pretty good idea of what's going on right away. :)

[std] use the new function type syntax for replacer in Json

---

src/core/meta.ml
src/typing/typeloadCheck.ml

Previously it would print "class" for interfaces too.

[typeload] fix error message for extending final interfaces

---

std/haxe/xml/Fast.hx

I noticed that the formatting here looked a bit off. Before:
After:

[std] fix formatting of the Fast.nodes code example

---

src/context/display/displayJson.ml

This makes things more consistent, right now this is the only `"display/"` method that uses a verb (and it's also inconsistent with the LSP).

[display] "display/findReferences" -> "display/references"

---

src/context/display/display.ml
src/context/display/displayEmitter.ml
src/context/display/displayJson.ml
src/core/displayTypes.ml
src/typing/typeload.ml
src/typing/typerDisplay.ml

This is used by the language server to [implement "Go to Type Definition"](https://github.com/vshaxe/haxe-languageserver/commit/67201c2bc27d09c0fb27a589228ae5a0db898db4):

[display] add display/typeDefinition

---

std/js/Promise.hx

This makes for better IDE support, since proper argument names can be generated now:

[std] use the new function type syntax for js.Promise.new()

---

src/typing/typerDisplay.ml

Currently seems to cause more issues than it solves.
I've already worked around the multi-line ranges that are sometimes reported in the language server (https://github.com/vshaxe/haxe-languageserver/commit/4a136ab0909c6876d97cfe2af6cca02ddefdbcf3), but this also seems to cause problems in other cases, e.g. here:
With this change, completion shows again:
Must be the replaceRange not containing the cursor position or something like that..

[display] revert f1248f5e (positions in generic toplevel) for now

---

src/core/displayTypes.ml
src/typing/typerDisplay.ml

I noticed that #7323 effectively removed some info from nested patterns. We can use the expected type info to offer generating [structure patterns](https://haxe.org/manual/lf-pattern-matching-structure.html) there.

[display] add expected types to CRPattern

---

src/context/display/displayToplevel.ml

The issue in the example was:
- explore_class_paths loop comes across flash.display.Bitmap (from std) and calls the callback
- the callback calls TypeloadParse.parse_module' on the file, but the package of the returned module is remapped to openfl.display due to --remap
- this then triggers the CompilationServer.remove_file call, removing the file from the cache
closes #7283

[display] fix class path exploration removing remapped files

---

std/lua/_std/sys/io/Process.hx

This is because on an embedded system without bash (a likely case when targeting lua), sys.io.Process() will seg fault.

Changed shell from bash to sh for process spawn.

---

std/haxe/EntryPoint.hx

Fix a small typo in the documentation: then -> the.

Fix docs typo
