codegen.ml, tests/unit/src/unit/issues/Issue2085.hx, tests/unit/src/unit/issues/Issue2902.hx, tests/unit/src/unit/issues/Issue3557.hx, tests/unit/src/unit/issues/Issue3615.hx
@ncannasse: Could you check if I'm using TLazy correctly here?
=> Generic delay

common.ml, gencommon.ml, interp.ml, main.ml, std/haxe/macro/Compiler.hx
I'm submitting this as a PR to first know if you have better suggestions for the naming/placing of this feature.
=> [java/cs] Initial implementation of javac-opt / cs-opt. Closes #3768

std/haxe/io/Bytes.hx, std/haxe/io/FPHelper.hx, std/haxe/io/Input.hx, std/haxe/io/Output.hx, std/js/_std/haxe/io/Bytes.hx, std/neko/NativeString.hx
This improves and cleanup bytes/float conversion. Waiting for unit tests results on all platforms to merge.
Also requires improved flash support using helper ByteArray and macro neko 2.1 builtins for faster IO
=> Faster Bytes

gencs.ml
=> [cs] generate "where" clauses for type constraints for @:nativeGen classes (closes #3526)

Makefile, Makefile.win, interp.ml
=> use process api for macros

analyzer.ml, codegen.ml, std/haxe/Serializer.hx, std/js/_std/Reflect.hx, tests/optimization/src/TestJs.hx
Also propagate TEnumParameter if it only appears once. Also remove duplicate variables in pattern matching.
=> Run local DCE on SSA form

std/cs/internal/Function.hx
Override "Equals" to do the comparison between Closures.
=> [cs] Closure missing compare operator? #3771

std/cs/_std/Type.hx, tests/unit/unit.html, tests/unit/unitstd/Type.unit.hx
This fixes issue #3389.
But I'm not sure if it is useful after reading through #3338, with cs enums having other mayor problems.
=> [cs] fix getEnumConstructs

tests/unit/src/unitstd/AnonFieldAccess.unit.hx
i added these for the python target, but i'm not sure if these should be part of the specification.
=> add tests for accessing core type fields hidden behind anons

genneko.ml, main.ml
There are also a haxelib and hxcpp patches to be done
=> [debian] Allow /usr/share as an installation directory. See #2890

main.ml
See #3779 and https://github.com/HaxeFoundation/ocamllibs/pull/12
=> use FindFirstFile to get proper module name casing

std/haxe/crypto/Adler32.hx, std/haxe/crypto/Crc32.hx, std/haxe/crypto/Hmac.hx, std/haxe/crypto/Sha1.hx, std/haxe/crypto/Sha224.hx, std/haxe/crypto/Sha256.hx
Class descriptions, in line of other classes in this package.
=> Crypto class documentation

Makefile, Makefile.win, main.ml
Making a PR to see if you agree to change the output format - I guess no one is parsing that output for fancy stuff?
=> Let `haxe -version` output version_extra too.

std/Lambda.hx
flatMap is a very useful function that would greatly enhance Lambda.hx
=> Add flatten and flatMap to Lambda.hx

std/haxe/remoting/AMFConnection.hx, std/haxe/remoting/AsyncConnection.hx, std/haxe/remoting/Context.hx, std/haxe/remoting/HttpAsyncConnection.hx, std/haxe/remoting/HttpConnection.hx, std/haxe/remoting/LocalConnection.hx, std/haxe/remoting/Proxy.hx, std/haxe/remoting/SocketConnection.hx
=> Remoting class documentation

std/php/Lib.hx, std/php/Web.hx
* Some missing function documentation
* Corrected markdown links
* Added some dots
=> Php additional documentation

std/neko/Random.hx, std/neko/vm/Deque.hx, std/neko/vm/Gc.hx, std/neko/vm/Lock.hx, std/neko/vm/Mutex.hx, std/neko/vm/Tls.hx, std/neko/vm/Ui.hx
Mostly copied from http://nekovm.org/doc/libs
=> neko.vm documentation

std/cs/Flags.hx
Reverts HaxeFoundation/haxe#4242
=> Revert "std/cs/Flags.hx documentation fix"

std/haxe/macro/Expr.hx
Parts based on the documentation of haxe.macro.Type.hx documentation.
Please double check. 
It has full stops :smile:
=> haxe.macro.Expr.hx documentation

std/php/_std/haxe/zip/Compress.hx, tests/unit/src/unitstd/haxe/zip/Compress.unit.hx
=> [php] Implements haxe.zip.Compress.run()

gencs.ml
Please check if this is the right fix :)
=> [C#] fixed error CS1560

std/php/_std/Type.hx, tests/unit/src/unit/issues/Issue4445.hx
PHP: surround array_unique with array_values in Type.getClassFields()
=> Fix  #4445

interp.ml
The debian neko package has been naming the libneko shared library as libneko.so.0, in which the .0 version is suggested by the [debian policy](https://www.debian.org/doc/debian-policy/ch-sharedlibs.html). Haxe macros however load only libneko.so, leads to issues as described in https://groups.google.com/forum/#!topic/haxelang/EkGQw5qCR-0
This PR changes the loading logic to try ["libneko.so"; "libneko.so.2"; "libneko.so.1"; "libneko.so.0"] in order.
=> [interp] try to load libneko.so.*

genjava.ml, genpy.ml, tests/unit/src/unit/issues/Issue4608.hx
This pull request fixes an error in the function that calculate hash code of string. (See #4608)
=> Fix issue #4608

std/neko/net/ThreadServer.hx
Documented neko.net.ThreadServer with information taken from: http://old.haxe.org/api/neko/net/threadserver
=> Documented neko.net.ThreadServer

std/cpp/_std/haxe/Int64.hx, std/cs/_std/haxe/Int64.hx, std/haxe/Int64.hx, std/haxe/Int64Helper.hx, std/java/_std/haxe/Int64.hx, tests/unit/src/unit/TestInt64.hx
Follow up to #3654 , updated for current development branch.
=> Add Int64.fromFloat and Int64.fromString.

std/cpp/net/ThreadServer.hx
As promised, documented cpp.net.ThreadServer with information taken from: http://old.haxe.org/api/neko/net/threadserver
Pretty much the same as #4634
=> Documented cpp.net.ThreadServer

std/php/Web.hx, std/php/_std/EReg.hx, tests/unit/src/unitstd/EReg.unit.hx
fix for #4629
fix for Ereg.replace problem #4657 #4430 (capture groups with 1 character)
=> [php] fixes for Ereg.replace and Web.getParams

std/js/_std/haxe/ds/IntMap.hx
closes https://github.com/HaxeFoundation/haxe/issues/4707
=> [JS] Make use of __js__ interpolation in haxe.ds.IntMap.keys

std/StdTypes.hx
=> StdTypes docs: backticks, typo fix, consistent ()

std/flash/Boot.hx
This is a cheap yet very impacting one.
Tested on my local haxe branch but not with full latest dev test suit. let's see if it pass all the tests.
=> Optimize regular array remove so that is does not allocate any longer

std/php/_std/Reflect.hx, tests/unit/src/unitstd/Reflect.unit.hx
Same pull request as before but from a seperate branch
=> Php reflection fixes

extra/extract.patch
=> patch flash extern

Makefile, src/json.ml
As requested, for future completion API.
=> add json serialization module

src/generators/gencommon.ml, std/haxe/crypto/Md5.hx, std/haxe/crypto/Sha1.hx, std/haxe/crypto/Sha256.hx, tests/unit/src/unit/issues/Issue5090.hx
charCodeAt returns a short on UTF-16 platforms; So convert them to bytes first on those platforms
Closes #5090
=> Fix crypto functions that use charCodeAt to get each byte from a String:

src/typing/typer.ml, tests/unit/src/unit/issues/Issue5231.hx
=> Allow typer to be resumed when typing underlying abstract types. 

std/php/_std/haxe/zip/Uncompress.hx, tests/unit/src/unit/issues/Issue2861.hx
This is needed to use `format.swf` in PHP 
(other PR to come on `format` to make `Inflate/Deflate` use `Compress/Uncompress` in PHP)
=> [php] added incomplete Compress / Uncompress implementation

std/haxe/Json.hx
=> small documentation fix Json

haxe.hxproj
This is useful to find types only in std
=> add std as classpath

std/python/_std/StringBuf.hx
See http://api.haxe.org/v/dev/StringBuf.html#get_length
=> Don't make accessor public

std/haxe/extern/EitherType.hx, std/haxe/extern/Rest.hx
small addition:
* add links to extern section in manual
* use tabs
=> haxe.extern documentation 

std/haxe/xml/Fast.hx, std/haxe/xml/Printer.hx
`haxe.xml.Fast` and `haxe.xml.Printer` documentation.
For those who still have to use xml.
=> haxe.xml documentation

src/typing/typeload.ml
The original one was, well, incomprehensible
=> Update error message

src/generators/gencpp.ml, std/cpp/_std/Type.hx, tests/RunCi.hx, tests/unit/compile-cppia-host.hxml, tests/unit/src/scripthost/Issue5351.hx, tests/unit/src/unit/issues/Issue5351.hx
=> [cpp] Make sure that the function vtable entries are set in the correct order

std/Any.hx, std/StdTypes.hx, tests/unit/src/unit/issues/Issue5322.hx
This implements [HXP-0001](https://github.com/HaxeFoundation/haxe-evolution/blob/master/proposals/0001-any.md) with documentation and tests.
More things to do:
* document and promote usage of Any in manual
* review the standard library and add #if'ed usage of Any, as mentioned in the original proposal.
=> add Any type (implements HXP-0001, closes #5322)

std/php/Boot.hx
As discussed here: https://github.com/HaxeFoundation/haxe/commit/1687918c60ca5d7093bfe7cb9a31ddc1248f7364#commitcomment-18753981
=> [php] fix _hx_exception_handler

std/lua/_std/Date.hx
https://github.com/HaxeFoundation/haxe/issues/5547
=> fix see issue

tests/unit/src/unit/issues/Issue5584.hx
This already passed Travis on my fork: https://travis-ci.org/Gama11/haxe/builds/157575368
=> Add a unit test for #5584

std/Array.hx
I *think* it should be "less than".
=> Fix doc of Array#slice

CONTRIBUTING.md, README.md
This changes some links to https in the readme.
Question: can URL in the repo description also be changed to https?
=> https links in README.md

std/python/lib/Threading.hx, std/python/lib/threading/Lock.hx, std/python/lib/threading/RLock.hx, std/python/lib/threading/Thread.hx
https://docs.python.org/3/library/threading.html
=> Preliminary implementation of python's threading externs

std/java/internal/StringExt.hx
=> [java] fixes charCodeAt for surrogate characters, matches the c# behaviour

src/generators/genpy.ml, src/optimization/dce.ml, std/python/internal/ArrayImpl.hx, std/python/internal/StringImpl.hx
=> cleanup python dce, fix #5820, fix #5817

std/hl/_std/sys/db/Sqlite.hx
haxe std class for hl SQLite lib
https://github.com/HaxeFoundation/hashlink/pull/29
=> add hl SQLite

src/generators/genphp.ml, src/generators/genphp7.ml, tests/unit/src/unit/issues/Issue4988.hx
=> [php] Fix for syntax erros on field access to `null`

std/cs/_std/sys/FileSystem.hx, std/php/_std/sys/FileSystem.hx, std/php7/_std/sys/FileSystem.hx, tests/RunCi.hx, tests/unit/src/unit/issues/Issue5742.hx
Fixes #5742 
However this commit changes behavior of those methods. So, despite it's a fix according to doc, it's also a somewhat breaking change :)
=> [php][php7] throw on failed FileSystem.deleteFile() and deleteDirectory()

extra/CHANGES.txt, src/generators/genphp.ml, std/php/Boot.hx, tests/unit/src/unit/issues/Issue5608.hx
=> Fixed exception thrown by `Reflect.fields(o)` when `o` is `Class<T>` (#5608)

README.md
=> Update README with stable download urls

src/optimization/dce.ml
So e.g. `try ... catch (e:ExternError) ...` marks `ExternError` as `@:directlyUsed` which makes e.g. genjs/genpy/genlua generate imports even if it's not used anywhere else.
=> [dce] don't forget to add @:directlyUsed to types used in catch variables

.travis.yml, tests/RunCi.hx
* Use neko PPA instead of compiling it.
* Install OCaml through opam.
* Remove PHP7 from the matrix, run it as part of normal linux tests instead.
=> Some travis cleanup

std/haxe/ds/BalancedTree.hx
As requested at [googlegroup](https://groups.google.com/forum/#!topic/haxelang/Z-3qiUgcc30).
=> `BalancedTree` implements `haxe.Constraints.IMap`

.gitignore, .merlin, .travis.yml, Makefile, appveyor.yml, src/compiler/globals.ml, src/compiler/server.ml, src/macro/hlmacro.ml, src/macro/interp.ml, src/macro/macroApi.ml, src/macro/macroContext.ml, std/haxe/macro/Context.hx
Requires `opam install rope` and `opam install ptmap`. See commit messages for the rest.
=> Some more random changes

src/generators/genpy.ml, std/Reflect.hx, std/python/Boot.hx, std/python/_std/Reflect.hx, std/python/internal/MethodClosure.hx, std/python/internal/UBuiltins.hx, tests/unit/src/unitstd/Reflect.unit.hx
=> extend documentation of Reflect.compareMethods and add more tests

extra/ImportAll.hx, extra/all.hxml, src/compiler/globals.ml, src/compiler/main.ml, src/compiler/server.ml, src/context/common.ml, src/optimization/analyzer.ml, src/optimization/analyzerTexpr.ml, std/Math.hx, std/Std.hx, std/StringTools.hx, std/haxe/CallStack.hx, std/haxe/Serializer.hx, std/haxe/crypto/Md5.hx, std/haxe/format/JsonParser.hx, std/haxe/macro/Compiler.hx, std/haxe/macro/Context.hx, std/haxe/macro/MacroStringTools.hx, std/haxe/macro/TypeTools.hx, std/haxe/unit/TestRunner.hx, std/haxe/xml/Parser.hx, tests/sys/src/ExitCode.hx, tests/sys/src/FileNames.hx, tests/sys/src/TestArguments.hx, tests/unit/src/unitstd/StringTools.unit.hx, tests/unit/src/unitstd/Type.unit.hx
This PR just adds some conditional compilation and prepares for the new macro interpreter target. I'm sending it separately to have a better overview of what is changing, and also to make sure it doesn't break anything unrelated.
The rest will follow soon.
=> Prepare for new macro interpreter

tests/unit/src/unit/issues/Issue6281.hx
see HaxeFoundation/hxcpp@5d16835
=> Re-enable the #6281 test on cppia

src/generators/genlua.ml
Here's a pull request for "flattened namespaces" in Lua.  This is pretty much equivalent to the js version.  It'll change references from haxe.ds.IntMap to __haxe_ds_IntMap.  The double underline prefix is there to prevent collisions with other modules.  Double underline isn't as fool-proof, but it's the best I can come up with.
@nadako just wanted to see if you had any other thoughts here.  I'm guessing we just want to use flat namespaces.  I didn't think there was a good reason to add in a flag, etc.
=> [lua] flatten module namespaces

src/compiler/main.ml, src/context/common.ml, src/syntax/lexer.ml
Use one-based error format, add -D old-error-format to keep zero-based behavior
=> Error Format change

src/macro/eval/evalExceptions.ml
=> [eval] fix inconsistent error formatting

src/generators/gencommon/initFunction.ml, src/generators/gencommon/interfaceVarsDeleteModf.ml, src/generators/gencommon/reflectionCFs.ml, src/generators/gencpp.ml, src/generators/gencs.ml, src/generators/genhl.ml, src/generators/genjava.ml, src/generators/genjs.ml, src/generators/genlua.ml, src/generators/genneko.ml, src/generators/genphp.ml, src/generators/genphp7.ml, src/generators/genpy.ml, src/generators/genswf9.ml, src/macro/eval/evalPrototype.ml, src/optimization/dce.ml, src/typing/type.ml, src/typing/typeload.ml, src/typing/typer.ml
Changed `is_extern_field` to reflect real purpose.
Waiting for CI.
=> Changed is_extern_field to is_physical_field

src/context/meta.ml, src/syntax/parser.mly
That way, it shows up in --help-metas.
=> Use Meta.Pos instead of Meta.Custom ":pos"

std/hl/_std/sys/ssl/Socket.hx
The socket must be ready before handshake()
=> (HL) Fixed non-blocking SSL Socket connect

src/context/meta.ml
It works for Lua as well, and for both classes and fields.
=> Update the docs for @:expose

std/haxe/macro/Printer.hx
For https://github.com/Simn/haxeparser/pull/40
=> Remove spaces around "in" in printBinop

std/haxe/MainLoop.hx
=> Update MainLoop.hx (doc)

std/haxe/Int64Helper.hx
Ref https://github.com/HaxeFoundation/haxe/issues/6623
=> add comment about (under|over)flow in float to Int64 conversion

src/macro/eval/evalStdLib.ml, std/haxe/CallStack.hx, std/php/_std/haxe/CallStack.hx
This PR adds column to `haxe.CallStack.StackItem.FilePos`. See #6662.
Opinions?
=> Added column to StackItem.FilePos (#662)

src/optimization/dce.ml, tests/unit/src/unit/issues/Issue6062.hx
=> [dce] keep constructor if any instance field is kept (fixes #6062)

src/compiler/main.ml, src/compiler/server.ml, src/context/common.ml
This is the base code for future resolving #4480 and for further imrpovement of compiler output.
=> Added kinds of compiler messages

std/haxe/format/JsonParser.hx, tests/unit/src/unit/issues/Issue5691.hx
Fix trailing character in Json declaration of boolean/array/number and object see #5691
=> Fix parsing of invalid json

src/codegen/gencommon/arraySpliceOptimization.ml, src/generators/gencs.ml, src/generators/genjava.ml
@waneck please review if this is what you wanted to do in #3962 and whether you can see some issues with this simple implementation
=> [cs/java] transform array.splice to array.spliceVoid when the result is unused (closes #3962)

std/php/_std/haxe/zip/Uncompress.hx, tests/unit/src/unitstd/haxe/zip/Compress.unit.hx, tests/unit/src/unitstd/haxe/zip/Uncompress.unit.hx
=> [php] Implement haxe.zip.Uncompress.execute()

src/optimization/dce.ml, tests/misc/projects/Issue6841/Main.hx, tests/misc/projects/Issue6841/Test.hx, tests/misc/projects/Issue6841/compile.hxml
=> Fix dce full with array join

extra/CHANGES.txt, src/optimization/optimizer.ml, tests/optimization/src/TestLocalDce.hx, tests/unit/src/unit/issues/Issue3792.hx
=> Fixed loop unrolling (closes #3784, fixes #3792)

src/macro/eval/evalStdLib.ml, std/cpp/_std/sys/io/File.hx, std/cs/_std/sys/io/File.hx, std/cs/io/NativeOutput.hx, std/eval/_std/sys/io/File.hx, std/hl/_std/sys/io/File.hx, std/java/_std/sys/io/File.hx, std/lua/_std/sys/io/File.hx, std/neko/_std/sys/io/File.hx, std/php/_std/sys/io/File.hx, std/python/_std/sys/io/File.hx, std/sys/io/File.hx, tests/unit/src/unitstd/sys/io/File.unit.hx
Fixes https://github.com/HaxeFoundation/haxe/issues/3467
Requires https://github.com/HaxeFoundation/hashlink/pull/114
=> Add File.update for writing to file without truncating

src/macro/eval/evalStdLib.ml, tests/misc/projects/Issue6922/Test.hx, tests/misc/projects/Issue6922/compile.hxml
`(unknown) : Uncaught exception Unexpected value VNull(null), expected object`
=> [eval] fix haxe.Log.trace when infos = null

std/haxe/http/HttpNodeJs.hx
Setting parameters along with POST data should be allowed.
=> Fix Http POST with parameters

src/typing/typer.ml, tests/unit/src/unit/issues/Issue6896.hx
Fixes https://github.com/HaxeFoundation/haxe/issues/6896
=> Avoid wrapping Null<T> into Null<Null<T>>

src/syntax/grammar.mly, tests/unit/src/unit/issues/Issue6948.hx
=> Allow bools as const params

src/typing/typeload.ml, tests/unit/src/unit/TestGeneric.hx, tests/unit/src/unit/TestType.hx
Fixes #3697 
This was surprisingly straightforward, maybe I'm missing something?
=> Allow structs as generic type params

src/typing/typeload.ml, tests/unit/src/unit/issues/Issue6952.hx
=> Fix EReg use as type parameter

std/haxe/http/HttpBase.hx
This is obviously a breaking change, but I want to get it over with before the chaining causes any more problems like in #6919.
=> [std] disable Http method chaining

src/macro/eval/evalContext.ml, src/macro/eval/evalEmitter.ml, src/macro/eval/evalEncode.ml, src/macro/eval/evalExceptions.ml, src/macro/eval/evalJit.ml, src/macro/eval/evalMain.ml, src/macro/eval/evalPrinting.ml, src/macro/eval/evalPrototype.ml, src/macro/eval/evalStdLib.ml, src/macro/eval/evalValue.ml
This removes a whole bunch of optimizations in eval in order to make it more maintainable. While these optimizations do help a little, I couldn't justify their complexity in relation to the benefit.
Also closes #6496.
=> Remove some eval optimizations

src/codegen/dotnet.ml, src/codegen/java.ml, src/codegen/swfLoader.ml, src/core/ast.ml, src/core/type.ml, src/macro/macroApi.ml, src/syntax/grammar.mly, src/syntax/reification.ml, src/typing/macroContext.ml, src/typing/magicTypes.ml, src/typing/typeload.ml, src/typing/typeloadFields.ml, tests/display/src/cases/Issue5999.hx, tests/display/src/cases/Issue6422.hx, tests/display/src/cases/PropertyAccessors.hx, tests/display/src/cases/Super.hx, tests/misc/projects/Issue1968/compile.hxml.stderr, tests/misc/projects/Issue3361/compile1-fail.hxml.stderr, tests/misc/projects/Issue3361/compile2-fail.hxml.stderr, tests/misc/projects/Issue3417/compile-fail.hxml.stderr, tests/misc/projects/Issue3726/compile-2-fail.hxml.stderr, tests/misc/projects/Issue6584/compile1-fail.hxml.stderr
Pretty big diff for what it does, but I don't think there's a way around keeping the accessor positions if we want to support this feature (and we do).
=> Override position

tests/display/.vscode/settings.json, tests/display/.vscode/tasks.json, tests/display/src/Macro.hx, tests/display/src/cases/IssueTemplate.hx
You can now select which one to run in the status bar:
The empty `IssueTemplate` is pretty handy for creating new tests / issues.
=> [display] allow running a single display test + add issue template

src/codegen/dotnet.ml, src/codegen/java.ml, src/context/display/findReferences.ml, src/core/ast.ml, src/core/display/completionItem.ml, src/macro/macroApi.ml, src/syntax/grammar.mly, src/syntax/reification.ml, src/typing/typeload.ml, src/typing/typer.ml, std/haxe/macro/Expr.hx, std/haxe/macro/Printer.hx, std/haxe/macro/Type.hx, std/haxe/rtti/CType.hx, tests/unit/src/unit/MyClass.hx, tests/unit/src/unit/issues/Issue3198.hx
Implementation of https://github.com/HaxeFoundation/haxe-evolution/pull/46 with minor deviations.
There's a strange CI failure going on which I cannot reproduce locally. Shouldn't be related, but I'll check again before merging.
closes #6565
closes #7006 
closes #7036
=> Add support for `Type & Type` syntax

std/haxe/display/JsonModuleTypes.hx
=> Update JsonAbstract.impl's type

std/js/html/compat/Float32Array.hx, std/js/html/compat/Float64Array.hx, std/js/html/compat/Uint8Array.hx
try to resolve #6685 when the `BytesBuffer` is growing, and i have tested it in IE8.
=> fix compat.Uint8Array.set

std/lua/_std/sys/io/Process.hx
ProcessInput did not have a close
=> Fix file handle leak -

src/context/display/displayFields.ml
=> [display] fix _Impl_ origin in field completion

src/compiler/main.ml, src/core/displayTypes.ml, src/typing/typeload.ml
=> [display] add isIntersectionType to CRStructExtension

src/context/display/displayEmitter.ml, src/context/display/displayFields.ml, src/context/display/displayToplevel.ml, src/core/display/completionItem.ml
Now they use the correct icons. :)
=> [display] fix kinds of enum fields in field completion, closes #5623

tests/unit/src/unit/issues/Issue7332.hx, tests/unit/src/unit/issues/Issue7334.hx, tests/unit/src/unit/issues/Issue7335.hx
(using a PR just to see if any other targets are failing)
=> Add tests for #7332, #7334 and #7335
